### ISSUE TITLE
Bibliotek for transformering av infomodeller - Mandatory felter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/modelldcatnotordf#2]
**Mandatory felter**
Denne oppgaven tar for seg å støtte med transformering av de obligatoriske feltene:
 
- [x] modelldcatno:InformationModel
-- dct:title
-- dct:description
-- dct:identifier
-- dct:publisher
-- dcat:theme

- [x] dcat:Catalog  (1) (0-n)
-- dct:description
-- dct:identifier
-- dct:title
-- dct:publisher
-- modelldcatno:model

- [x] foaf:Agent 
-- foaf:name

**Comment by frederik-ronnevig** [comment]
Gjenstående estimat (2 d)

**Comment by lillelars** [comment]
Ferdigstilt. Lukker denne saken.
