### ISSUE TITLE
Utvide bibliotek med skos:ConceptScheme -- dct:title

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/modelldcatnotordf#201]
(eget biblotek til dette - med avhengigheter fra både informasjonsmodell-biblioteket, og datasettbiblioteket)
https://data.norge.no/specification/dcat-ap-no/#Katalog-temaer

TODO: 
- [x] Ny klasse ConceptScheme
- [x] dct:title for skos:ConceptScheme

**Comment by frederik-ronnevig** [comment]
Det har bare ikke blitt gjort før fordi vi aldri tok den diskusjonen ferdig om hvor det skulle ligge :innocent:
