### ISSUE TITLE
Bibliotek for transformering av infomodeller - Recommended felter

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/modelldcatnotordf#3]
**Recommended felter**
Denne oppgaven tar for seg å støtte transformering av de anbefalte feltene:

- [x] modelldcatno:RootObjectType (1)

- [x] dct:LicenseDocument
-- dct:type

- [x] modeldcatno:Modelelement (1)
-- dct:title
-- dct:identifier
-- dct:subject
-- modeldcatno:hasProperty

- [x] modeldcatno:Property (1)
-- dct:identifier
-- dct:title
-- xsd:minOccurs
-- xsd:maxOccurs
-- dct:subject

- [x] modelldcatno:CodeElement (1)
-- dct:identifier
-- skos:prefLabel
-- dct:subject
-- skos:notation
-- xkos:next
-- xkos:previous
-- skos:topConceptOf
-- skos:inScheme

- [x] modelldcatno:Datatype (1)

- [x] modelldcatno:Attribute

- [x] modelldcatno:hasDataType

- [x] modelldcatno:containObjectType

- [x] modelldcatno:hasSimpleType

- [x] modelldcatno:hasValuesFrom (1)

- [x] modelldcatno:CodeList
-- skos:inScheme
-- skos:topConceptOf

- [x] modelldcatno:SimpleType
-- modelldcatno:typeDefinitionReference

- [x] modelldcatno:ObjectType (1)

- [x] modelldcatno:Role
-- modelldcatno:hasObjectType

- [x] modelldcatno:InformationModel (1)
-- modelldcatno:informationModelIdentifier
-- dct:subject
-- dct:license
-- modelldcatno:containsModelElement
-- dcat:contactPoint

- [x] dcat:Catalog (1)
-- foaf:homePage
-- dct:issued
-- dct:language
-- dct:spatial
-- dct:license
-- dct:modified

- [x] foaf:Document
-- dct:title
-- dct:language

- [ ] vcard:Kind

- [x] foaf:Agent
-- dct:identifier
-- dct:type

**Comment by frederik-ronnevig** [comment]
Gjenstående estimat : (9 d)

**Comment by lillelars** [comment]
Lukker denne. Tar ut  vcard:Kind til eget issue: https://github.com/Informasjonsforvaltning/datacatalogtordf/issues/24
