### ISSUE TITLE
Ta i bruk nox-poetry

### ISSUE THREAD

**Issue by frederik-ronnevig** [Informasjonsforvaltning/modelldcatnotordf#38]
Nox og poetry har litt samværsproblematikk, som kan gi seg utslag i knekt ci/cd. Fixen er å bruke nox-poetry i tilegg. https://pypi.org/project/nox-poetry/

Gjør følgende:

```
          pip install nox==2020.8.22
          pip install poetry==1.1.4
          pip install nox-poetry
```

i workflow. Merk moderne versjonaer, som ikke er 1000-vis av år gamle.

Sjekk:

https://github.com/Informasjonsforvaltning/dataservice-publisher

(https://github.com/Informasjonsforvaltning/dataservice-publisher/search?q=pip+install)

Grunnen til å pinne nox- og poetryversjoner, er at for å kjøre samme versjon i GitHub workflows som kjøres lokalt.

Se også:
https://github.com/Informasjonsforvaltning/fdk-harvester-bff/commit/9d32648f700b807236a94074b53b152a5ccfd2e5

**Comment by stigbd** [comment]
I tillegg må du ta i bruk nox-poetry i noxfile.py:
```
import nox
from nox.sessions import Session
import nox_poetry  # noqa: F401
```
Fjerne all bruk av  `install_with_constraints` . Sjå feks https://github.com/Informasjonsforvaltning/dataservice-publisher/commit/bff52e7b13cfff68678185ac2aa49f34cc57be4d

**Comment by frederik-ronnevig** [comment]
Takk for tips @stigbd !
