### ISSUE TITLE
Bibliotek for transformering av infomodeller - Optional 

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/modelldcatnotordf#4]
**Optional felter**
Denne oppgaven tar for seg å støtte transformering av de feltene som er valgfrie:

- [x] modelldcatno:hasType (1)
-- modelldcatno:isAbstractionOf
-- modelldcatno:contains
-- modeldcatno:hasMember
-- modelldcatno:hasSupplier
-- modelldcatno:hasGeneralConcept
-- modelldcatno:refersTo
-- modelldcatno:hasSome

- [x] modelldcatno:Abstraction (1)

- [x] modelldcatno:Composition

- [x] modelldcatno:Collection

- [x] modelldcatno:Realization

- [x] modelldcatno:Specialization (1)

- [x] modelldcatno:Association

- [x] modelldcatno:Choice

- [x] modelldcatno:Note
-- modelldcatno:propertyNote

- [x] dcat:Catalog (1)
- [x] dct:hasPart
- [x] dct:isPartOf
- [x] dcat:themeTaxonomy
- [x] dct:spatial

- [x] dct:Location (1)
- [x] dcat:bbox
- [x] dcat:centroid
- [x] locn:geometry

- [x] foaf:Document
-- dct:format

- [x] dct:PeriodOfTime (1)

- [x] dct:LinguisticSystem

- [x] schema:ContactPoint

- [x] modelldcatno:InformationModel (1)
- [x] dcat:keyword
- [x] dct:issued
- [x] dct:temporal
- [x] dct:language
- [x] dct:type
- [x] dct:modified
- [x] owl:versionInfo
- [x] adms:versionNotes (1)
- [x] foaf:homepage
- [x] adms:status
- [x] dct:hasFormat
- [x] dct:creator
- [x] dct:spatial
- [x] dct:replaces
- [x] dct:isReplacedBy
- [x] dct:hasPart
- [x] dct:isPartOf

- [x] modeldcatno:Property (1)
-- dct:description
-- modelldcatno:sequenceNumber
-- modelldcatno:belongsToModule
-- modelldcatno:relationPropertyLabel
--modelldcatno:formsSymmetryWith

- [x] modelldcatno:SimpleType(1)
-- xsd:length
-- xsd:fractionDigits
-- xsd:maxLength
-- xsd:minLength
-- xsd:totalDigits
-- xsd:maxInclusive
-- xsd:minInclusive
-- xsd:pattern

- [x] modelldcatno:CodeList (1)
-- modelldcatno:codeListReference

- [x] modelldcatno:CodeElement
-- skos:altLabel
-- skos:definition
-- skos:example
-- skos:hiddenLabel
-- skos:note
-- xkos:exclusionNote
-- xkos:inclusionNote

//referanse mot optional. Håndteres senere.
- [x] skos:Concept (1) 
- [x] skos:ConceptScheme 
-- dct:title

**Comment by frederik-ronnevig** [comment]
Gjenstående estimat : (11 d)
