### ISSUE TITLE
Støtte for titler uten språktagg

### ISSUE THREAD

**Issue by frederik-ronnevig** [Informasjonsforvaltning/modelldcatnotordf#60]
Det rapporteres fra behovseiere at det skal være mulig å støtte titler uten angitt språk

**Comment by lillelars** [comment]
@stigbd er det blitt avklart hvordan vi ønsker å løse denne enda?

**Comment by stigbd** [comment]
Tittel er vel i dette biblioteket Literals. Og language tag er optional, så det er ingenting i vegen for den,

**Comment by frederik-ronnevig** [comment]
Jeg har laget en liten test som viser kodeeksempel på hvordan man bruker titler uten språktagg. PR:

https://github.com/Informasjonsforvaltning/modelldcatnotordf/pull/107

Lukker saken :-)
