### ISSUE TITLE
Forbedre serialisering av object properties

### ISSUE THREAD

**Issue by frederik-ronnevig** [Informasjonsforvaltning/modelldcatnotordf#63]
En slik referanse vil vel hovedsaklig bety eksterne kodelister, dette vil i så fall bare ende opp med en del tomme ressurser

_Originally posted by @NilsOveTen in https://github.com/Informasjonsforvaltning/modelldcatnotordf/pull/62#discussion_r560720507_

Når det eneste som ligger på objektet er en identifier skal ikke hele objektet serialiseres ved referanse, kun selve 
referansen. 

_**Her må det avklares om**_ 
-  Hvis det finnes andre properties på objektet, skal det da med? 
-  Hvis objektet ikke har en identifier, skal det da med? Altså BNodes? 

- [x] _subject: List[Union[Concept, URI]]
- [x] _modelelements: List[Union[ModelElement, URI]]
- [x] _licensedocument: Union[LicenseDocument, URI]

- [x] _publisher: Agent
- [x] _replaces: List[InformationModel]
- [x] _is_replaced_by: List[InformationModel]
- [x] _has_part: List[InformationModel]
- [x] _is_part_of: List[InformationModel]
- _contactpoints: List[Contact] (utgår fordi _contactpoints kun kan være Bnode)
-  _locations: List[Location]  (utgår fordi _locations kun kan være Bnode)
- [x] _dct_type: Concept
- [x] _status: Concept
-  _creator: str (utgår fordi _creator serialiseres av superklassen Resource i dcat)
- [x] _has_format: List[FoafDocument]
- _temporal: List[PeriodOfTime]  (utgår fordi _temporal bare kan være blank node)
- [x] _has_property: List[ModelProperty]
- [x] _subject: Concept
- [x] _has_type: List[ModelElement]
- [x] _subject: Concept
- [x] _forms_symmetry_with: ModelProperty
- [x] _has_object_type: ObjectType
- [x] _contains: ModelElement
- [x] _has_member: ModelElement
- [x] _refers_to: ModelElement
- [x] _has_some: List[ModelElement]
- [x] _contains_object_type: ObjectType  
- [x] _has_simple_type: SimpleType
- [x] _has_data_type: DataType
- [x] _has_value_from: CodeList
- [x] _has_general_concept: ModelElement
- [x] _has_supplier: ModelElement
- [x] _is_abstraction_of: ModelElement
- [x] _code_list_reference: CodeList
- [x] _subject: Concept
- [x] _in_scheme: List[CodeList]
- [x] _top_concept_of: List[CodeList]
- [x] _next_element: CodeElement
- [x] _previous_element: CodeElement
- [x] _type: List[Concept]

**Comment by stigbd** [comment]
Prinsipielt så meiner eg dette:
1. Dersom bruker instanserer ei klasse (med eller uten identifikator) i biblioteket og angir instansen som object i triplet, skal objektet opprettes, evt som BNode.
2. Dersom bruker _ikkje_ instanserer klassen, men angir en uri som object i triplet, skal _ikkje_ objektet opprettes.

Eksempel som illustrerer (1):
```
c = Catalog()
c.identifier = ":my_catalog"
c.dataset.append(":my_dataset")
c.to_rdf()

# gir output:
<:my_catalog> a dcat:Catalog ;
   dcat:dataset <:my_dataset> ;
.
```
Eksempel som illustrerer (2):
```
c = Catalog()
c.identifier = ":my_catalog"
d = Dataset()
d.identifier = ":my_dataset"
c.dataset.append(d)
c.to_rdf()

# gir output:
<:my_catalog> a dcat:Catalog ;
   dcat:dataset <:my_dataset> ;
.
<:my_dataset> a dcat:Dataset
.
```

**Comment by NilsOveTen** [comment]
> Prinsipielt så meiner eg dette:
> blablabla

I så fall må bibliotekene ta høyde for at samtlige felter som tar et objekt også kan være en uri av type str

**Comment by frederik-ronnevig** [comment]
Det siste som @NilsOveTen sier der kan vi fikse ganske enkelt. @Chlenix foreslo i en sak å bruke f.eks 'typing.Union[URIRef, ModelElement]' 

Jeg tenker kanskje å prioritere denne saken snart, hvis det er stemning for det

**Comment by NilsOveTen** [comment]
> Det siste som @NilsOveTen sier der kan vi fikse ganske enkelt. @Chlenix foreslo i en sak å bruke f.eks 'typing.Union[URIRef, ModelElement]'
> 
> Jeg tenker kanskje å prioritere denne saken snart, hvis det er stemning for det

:+1:

**Comment by frederik-ronnevig** [comment]
I samme slengen så kan det kanskje være bra å gå igjennom alle felter som har range til datatyper utenfor modellen og legge på disse? F.eks

```      <http://example.com/documents/1> a foaf:Document;
                dct:language "http://example.com/languages/1"^^dct:LinguisticSystem ```
